import { useRef } from "react";
import { 
  MapPin, 
  Calendar, 
  Clock, 
  User, 
  BookOpen, 
  Hash, 
  Printer, 
  Download, 
  RefreshCw,
  CheckCircle2,
  Building
} from "lucide-react";

interface AllocationResult {
  matricNumber: string;
  studentName: string;
  department: string;
  level: string;
  hall: string;
  seatNumber: string;
  date: string;
  time: string;
  course: string;
}

interface ResultCardProps {
  result: AllocationResult;
  onNewSearch: () => void;
}

const ResultCard = ({ result, onNewSearch }: ResultCardProps) => {
  const resultRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const printContent = resultRef.current?.innerHTML;
    if (!printContent) return;

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Exam Hall Allocation - ${result.matricNumber}</title>
          <style>
            body { 
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
              padding: 40px; 
              max-width: 600px; 
              margin: 0 auto;
              color: #1a1a2e;
            }
            .header { 
              text-align: center; 
              margin-bottom: 30px; 
              padding-bottom: 20px;
              border-bottom: 2px solid #16a085;
            }
            .header h1 { 
              color: #1a1a2e; 
              font-size: 24px; 
              margin-bottom: 5px;
            }
            .header p { 
              color: #666; 
              font-size: 14px;
            }
            .hall-badge {
              background: linear-gradient(135deg, #1a1a2e, #16a085);
              color: white;
              padding: 20px;
              border-radius: 12px;
              text-align: center;
              margin-bottom: 25px;
            }
            .hall-badge h2 {
              font-size: 36px;
              margin: 0 0 5px 0;
            }
            .hall-badge p {
              margin: 0;
              opacity: 0.8;
            }
            .info-grid {
              display: grid;
              gap: 15px;
            }
            .info-item {
              display: flex;
              justify-content: space-between;
              padding: 12px 0;
              border-bottom: 1px solid #eee;
            }
            .info-label { 
              color: #666; 
              font-weight: 500;
            }
            .info-value { 
              color: #1a1a2e; 
              font-weight: 600;
            }
            .footer {
              margin-top: 30px;
              padding-top: 20px;
              border-top: 1px solid #eee;
              text-align: center;
              color: #999;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>📚 Examination Hall Allocation</h1>
            <p>Official Hall Assignment Document</p>
          </div>
          <div class="hall-badge">
            <h2>${result.hall}</h2>
            <p>Seat: ${result.seatNumber}</p>
          </div>
          <div class="info-grid">
            <div class="info-item">
              <span class="info-label">Matriculation No.</span>
              <span class="info-value">${result.matricNumber}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Department</span>
              <span class="info-value">${result.department}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Level</span>
              <span class="info-value">${result.level}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Course</span>
              <span class="info-value">${result.course}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Date</span>
              <span class="info-value">${result.date}</span>
            </div>
            <div class="info-item">
              <span class="info-label">Time</span>
              <span class="info-value">${result.time}</span>
            </div>
          </div>
          <div class="footer">
            <p>Generated by ExamHall Allocation System</p>
            <p>Please arrive 30 minutes before your exam time</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleDownload = () => {
    const content = `
EXAMINATION HALL ALLOCATION
===========================

Hall: ${result.hall}
Seat Number: ${result.seatNumber}

STUDENT INFORMATION
-------------------
Matriculation No.: ${result.matricNumber}
Department: ${result.department}
Level: ${result.level}

EXAM DETAILS
------------
Course: ${result.course}
Date: ${result.date}
Time: ${result.time}

===========================
Please arrive 30 minutes before your exam time.
Generated by ExamHall Allocation System
    `;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `hall-allocation-${result.matricNumber}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-scale-in" ref={resultRef}>
      {/* Success Header */}
      <div className="text-center mb-6">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-secondary/10 mb-4 animate-bounce-gentle">
          <CheckCircle2 className="w-8 h-8 text-secondary" />
        </div>
        <h2 className="font-poppins font-bold text-2xl md:text-3xl text-foreground mb-2">
          Hall Found!
        </h2>
        <p className="text-muted-foreground">
          Your examination hall has been successfully located
        </p>
      </div>

      {/* Main Result Card */}
      <div className="glass-card overflow-hidden">
        {/* Hall Badge */}
        <div className="bg-hero-pattern p-8 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary-foreground/20 text-primary-foreground text-sm mb-4">
            <Building className="w-4 h-4" />
            <span>Your Assigned Hall</span>
          </div>
          <h3 className="font-poppins font-bold text-4xl md:text-5xl text-primary-foreground mb-2">
            {result.hall}
          </h3>
          <p className="text-xl text-accent font-semibold">
            Seat: {result.seatNumber}
          </p>
        </div>

        {/* Info Grid */}
        <div className="p-6 md:p-8 space-y-4">
          <div className="grid md:grid-cols-2 gap-4">
            {/* Student Info */}
            <div className="flex items-start gap-4 p-4 rounded-xl bg-muted/50">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                <User className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Matriculation No.</p>
                <p className="font-semibold text-foreground">{result.matricNumber}</p>
              </div>
            </div>

            <div className="flex items-start gap-4 p-4 rounded-xl bg-muted/50">
              <div className="w-10 h-10 rounded-lg bg-secondary/10 flex items-center justify-center flex-shrink-0">
                <BookOpen className="w-5 h-5 text-secondary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Department</p>
                <p className="font-semibold text-foreground">{result.department}</p>
              </div>
            </div>

            <div className="flex items-start gap-4 p-4 rounded-xl bg-muted/50">
              <div className="w-10 h-10 rounded-lg bg-accent/10 flex items-center justify-center flex-shrink-0">
                <Hash className="w-5 h-5 text-accent" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Course Code</p>
                <p className="font-semibold text-foreground">{result.course}</p>
              </div>
            </div>

            <div className="flex items-start gap-4 p-4 rounded-xl bg-muted/50">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                <MapPin className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Level</p>
                <p className="font-semibold text-foreground">{result.level}</p>
              </div>
            </div>
          </div>

          {/* Date & Time */}
          <div className="grid md:grid-cols-2 gap-4 pt-4 border-t border-border">
            <div className="flex items-center gap-4 p-4 rounded-xl bg-secondary/5 border border-secondary/20">
              <div className="w-12 h-12 rounded-xl bg-secondary/10 flex items-center justify-center">
                <Calendar className="w-6 h-6 text-secondary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Exam Date</p>
                <p className="font-semibold text-foreground text-lg">{result.date}</p>
              </div>
            </div>

            <div className="flex items-center gap-4 p-4 rounded-xl bg-accent/5 border border-accent/20">
              <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center">
                <Clock className="w-6 h-6 text-accent" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Exam Time</p>
                <p className="font-semibold text-foreground text-lg">{result.time}</p>
              </div>
            </div>
          </div>

          {/* Important Notice */}
          <div className="p-4 rounded-xl bg-primary/5 border border-primary/20 mt-4">
            <p className="text-sm text-primary font-medium">
              📌 Please arrive at least 30 minutes before your exam time. Bring your student ID and examination permit.
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 pt-0 flex flex-col sm:flex-row gap-3">
          <button
            onClick={handlePrint}
            className="flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground font-medium hover:bg-primary/90 transition-all duration-300"
          >
            <Printer className="w-5 h-5" />
            <span>Print Result</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-secondary text-secondary-foreground font-medium hover:bg-secondary/90 transition-all duration-300"
          >
            <Download className="w-5 h-5" />
            <span>Download</span>
          </button>
          <button
            onClick={onNewSearch}
            className="flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl border-2 border-border text-foreground font-medium hover:bg-muted transition-all duration-300"
          >
            <RefreshCw className="w-5 h-5" />
            <span>New Search</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default ResultCard;
